# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: deploy to hexo blog
      run: |
        git config --global user.name jiandahao
        git config --global user.email jiandahao@gmail.com
        cd ..
        export TOKEN="${{ secrets.GH_TOKEN }}"
        git clone -b hexo --depth 1 https://${TOKEN}@github.com/BugSurvivor/BugSurvivor.github.io.git
        cp -a notes BugSurvivor.github.io/source/_posts
        rm -rf BugSurvivor.github.io/source/_posts/notes/.git
        rm -rf BugSurvivor.github.io/source/_posts/notes/.github
        cd BugSurvivor.github.io
        git add --all && git commit -m"update notes" && git push origin hexo
        
